### PR TITLE
DAS-1744 - Branches v1

### PR DESCRIPTION
**Pull request by Klemen1337**
https://tillhub.atlassian.net/browse/DAS-1744

### CODE REVIEW

**Comment by erezsob** [comment]
Refer to newer test files in order to write less boilerplate-y tests
https://github.com/tillhub/tillhub-sdk-javascript/blob/master/test/transactions_items_v2/export.test.ts

**Review by erezsob — CHANGES_REQUESTED** [review]
Refactor tests

**Comment by Klemen1337** [comment]
> Refactor tests

Done

**Review by erezsob — APPROVED** [review]

**Comment by Klemen1337** [comment]
🚀

**Pull request merged**
